namespace: kube-system

resources:
  - 01-headless-service.yaml
  - 02-statefulset.yaml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: redis-conf
    files:
      - redis.conf
